name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v4.4.3
    
    
